[package]
name = "wasm86-compiler"
version.workspace = true
edition.workspace = true
license.workspace = true
publish.workspace = true

[dependencies]
wasm-encoder = { version = "=0.254.0", default-features = false }

[dev-dependencies]
wasmparser = { version = "=0.224.1", default-features = false, features = ["std"] }
