[package]
name = "wasm86-compiler"
version.workspace = true
edition.workspace = true
license.workspace = true
publish.workspace = true

[dependencies]
wasm-encoder.workspace = true

[dev-dependencies]
serde.workspace = true
wasm86-test-support.workspace = true
wasmparser = { version = "=0.224.1", default-features = false, features = ["std", "validate"] }
wasmtime.workspace = true
