[package]
name = "wasm86-compiler"
version.workspace = true
edition.workspace = true
license.workspace = true
publish.workspace = true

[dependencies]
hashbrown = { version = "=0.15.5", default-features = false }
rustc-hash = "=2.1.3"
wasm-encoder.workspace = true

[dev-dependencies]
serde.workspace = true
wasm86-test-support.workspace = true
wasmparser = { version = "=0.224.1", default-features = false, features = ["features", "std", "validate"] }
wasmtime.workspace = true
